### ISSUE TITLE
common statistics season display

### ISSUE THREAD

**Issue by sthiebaut05** [calypso-science/Toto#3]
in the output xls file, It displays some year number (e.g. 2006,2007) instead of "summer", "winter"...

**Comment by mymyrere** [comment]
Can you tell me which season option you tried? I can't reproduce the error

**Comment by sthiebaut05** [comment]
Sorry for the late reply. I can't reproduce the error either and I can't remember which data file generated this issue. Never mind, I will keep you posted if this occurs again.
