### ISSUE TITLE
Data Manipulation -> Spike removal issue

### ISSUE THREAD

**Issue by sthiebaut05** [calypso-science/Toto#5]
It doesn't look to work. I tried with a sea level time series, selected height= 0.5, clicked "try", but it didn't remove the upper peak, see attached snapshot.
![despike](https://user-images.githubusercontent.com/8619420/140376732-7f0bdbda-9781-4f8f-8348-2222c616b476.png)

**Comment by mymyrere** [comment]
I think you miss-used the value height, you probably meant threshold.
This function is a wrapper of the Scipy function https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.find_peaks.html
