### ISSUE TITLE
Wave -> Wave Spectra

### ISSUE THREAD

**Issue by sthiebaut05** [calypso-science/Toto#8]
See below snapshots, it shouldn't start from 2h period.
that's from a 1-sec interval sea level time series
![wavespec](https://user-images.githubusercontent.com/8619420/140728184-e1353f9b-7f47-4736-b2b9-3cad9dd388ac.png)
![geraldton_24feb2013_Spec](https://user-images.githubusercontent.com/8619420/140728221-bc5d255d-138c-4b47-9e47-145c0c387bd0.png)

**Comment by mymyrere** [comment]
This was corrected a long time ago, I don't think you are using the latest version
