### ISSUE TITLE
Wave -> wavelet analysis

### ISSUE THREAD

**Issue by sthiebaut05** [calypso-science/Toto#9]
See below snapshots, the period range selected is 10-1000 s, but the output figure shows from 8-1024 years.
![wavelet](https://user-images.githubusercontent.com/8619420/140730735-1ecbb74e-7790-4aff-a6cf-3f88d77cec74.png)
![geraldton_24feb2013_Wavelet](https://user-images.githubusercontent.com/8619420/140730781-28c0c84a-1752-411b-bc2a-c822ef2a9380.png)

**Comment by mymyrere** [comment]
Thanks, bug corrected
